# Generated by Django 4.1.3 on 2022-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_upload",
            field=models.ImageField(
                blank=True,
                default="event/images/default_e.jpg",
                null=True,
                upload_to="event/images",
                verbose_name="Image upload (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eating", "Eating"),
                    ("sport", "Sport"),
                    ("movie", "Movie"),
                    ("party", "Party"),
                    ("education", "Education"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type (optional)",
            ),
        ),
    ]
