# Generated by Django 4.1.1 on 2022-10-21 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Hello_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user_set",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
