# Generated by Django 4.1.1 on 2022-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile_images/images/default.jpg",
                upload_to="profile_images/images/",
            ),
        ),
    ]
