# Generated by Django 4.1.3 on 2022-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="joined",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="participant",
            field=models.PositiveIntegerField(default=1, verbose_name="Participant"),
        ),
    ]
