# Generated by Django 4.1.3 on 2022-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_upload",
            field=models.ImageField(
                blank=True,
                default="event/images/default_i5zu2p.jpg",
                null=True,
                upload_to="event/images",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile/images/default_cwudrj.jpg", upload_to="profile/images"
            ),
        ),
    ]
