# Generated by Django 4.1.3 on 2022-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0002_alter_event_image_upload_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=15, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.CharField(max_length=30, verbose_name="Place"),
        ),
    ]
