# Generated by Django 4.1.3 on 2022-11-17 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0002_alter_event_joined_alter_event_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2022, 11, 17, 7, 22, 54, 830257, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Time",
            ),
        ),
    ]
