# Generated by Django 4.1.2 on 2022-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="...", max_length=50),
        ),
    ]
