# Generated by Django 4.1.3 on 2022-11-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0003_alter_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(verbose_name="Time"),
        ),
    ]
