# Generated by Django 4.1.3 on 2022-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0003_key_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantofevent",
            name="get_key",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
