# Generated by Django 4.1.1 on 2022-10-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Hello_Buddy", "0004_remove_event_user_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manytomany",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Hello_Buddy.event",
            ),
        ),
        migrations.AlterField(
            model_name="manytomany",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
