# Generated by Django 4.1.3 on 2022-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0004_participantofevent_get_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantofevent",
            name="get_key",
            field=models.BooleanField(null=True),
        ),
    ]
