# Generated by Django 4.1.3 on 2022-11-17 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0004_alter_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(
                default=datetime.date(2022, 11, 18), verbose_name="Date"
            ),
        ),
    ]
