# Generated by Django 4.1.1 on 2022-10-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hello_Buddy", "0005_alter_manytomany_food_alter_manytomany_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manytomany", old_name="food", new_name="event",
        ),
    ]
